-- 
-- 
-- CREATE TABLES
-- 
-- 
CREATE TABLE IF NOT EXISTS USERS (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	ACCOUNT_TYPE VARCHAR(50) DEFAULT 'BASIC ACCESS',
	USERNAMEACCOUNT VARCHAR(20) UNIQUE NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTH (
	ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
	TOKEN_ACCESS VARCHAR(30) NOT NULL,
	USER_ID INTEGER NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

-- 
-- 
-- ALTER TABLE TO MODIFY COLUMN STRUCTURE
-- 
-- 
ALTER TABLE USERS RENAME COLUMN USERNAMEACCOUNT TO USER_NAME_ACCOUNT;
ALTER TABLE AUTH CHANGE COLUMN TOKEN_ACCESS TOKEN_ACCESS VARCHAR(50) UNIQUE NOT NULL;
ALTER TABLE USERS ADD CONSTRAINT CHECK_INFO_LENGTH CHECK (CHAR_LENGTH(USER_NAME_ACCOUNT) BETWEEN 5 AND 20);
ALTER TABLE USERS DROP CONSTRAINT CHECK_INFO_LENGTH;

-- 
-- 
-- INSERT DATA INTO TABLES
-- 
-- 
INSERT INTO USERS (NAME, EMAIL, ACCOUNT_TYPE, USER_NAME_ACCOUNT, PASSWORD) VALUES ('RUANSLV77', 'RUAN@GMAIL.COM', 'ADMIN', 'SILVA94', 'SLV_77@USR#99');
INSERT INTO USERS (NAME, EMAIL, USER_NAME_ACCOUNT, PASSWORD) VALUES ('TEST', 'TES@GMAIL.COM', 'TS', 'TX9819VB11');
INSERT INTO USERS (NAME, EMAIL, ACCOUNT_TYPE, USER_NAME_ACCOUNT, PASSWORD) 
VALUES ('JULIA', 'JULIA@GMAIL.COM', DEFAULT, 'JU98TTTT', 'JXXXX'),
('ROBERTO', 'ROBS@GMAIL.COM', 'MODERATE', 'ROBSZX', 'RB29@OC'),
('CLIB', 'CLIB@GMAIL.COM', 'PREMIUM', 'AX999999999', 'CCLIBTV');

INSERT INTO AUTH (TOKEN_ACCESS, USER_ID) VALUES ('29BX4430&', 11);
INSERT INTO AUTH (TOKEN_ACCESS, USER_ID) VALUES ('21BX4499!', 12);

-- 
-- 
-- SHOW DATA REGISTER INTO TABLES
-- 
-- 
SELECT * FROM USERS U;
SELECT * FROM AUTH A;
SELECT * FROM USERS U WHERE U.NAME IS NULL OR LOWER(U.NAME) LIKE LOWER(CONCAT('%', '7', '%'));
SELECT A.TOKEN_ACCESS, U.USER_NAME_ACCOUNT, U.EMAIL, U.ACCOUNT_TYPE FROM AUTH A INNER JOIN USERS U ON A.USER_ID = U.ID WHERE U.ID = 11;
SELECT A.TOKEN_ACCESS, U.USER_NAME_ACCOUNT, U.EMAIL, U.ACCOUNT_TYPE FROM AUTH A INNER JOIN USERS U ON A.USER_ID = U.ID;

-- 
-- 
-- UPDATE DATA WHERE
-- 
-- 
UPDATE USERS U SET U.ACCOUNT_TYPE = DEFAULT; -- DANGER, IF YOU USE THIS QUERY COMMAND LINE, THEN CHANGE ALL COLUMN VALUE IN ALL DATA.
UPDATE USERS U SET U.NAME = 'SALAMO TRISTE' WHERE U.ID = 11;

-- 
-- 
-- CLEAR/DELETE DATA INTO TABLE
-- 
-- 
DELETE FROM USERS; 	-- DANGER, IF YOU USE THIS QUERY COMMAND LINE, THEN DELETE ALL DATA.
DELETE FROM AUTH;	-- DANGER, IF YOU USE THIS QUERY COMMAND LINE, THEN DELETE ALL DATA.
DELETE FROM USERS U WHERE U.ID = 5;


-- 
-- 
-- DESCRIBE COLUMNS ON TABLE
-- 
-- 
SHOW COLUMNS FROM USERS;
SHOW COLUMNS FROM AUTH;